### ISSUE TITLE
Generate stats for words

### ISSUE THREAD

**Issue by Mte90** [Mte90/SyntaxAutoFix#26]
Can be interesting to see what are the most typos of the writer.
Generating a json with this kind of statistics with a simple UI can be an interesting implementation.

**Comment by Mte90** [comment]
the ticket is open for everyone :-)

**Comment by mirkoperillo** [comment]
Ok, I start working on it.
My idea is collect typos in a stats.json file and reading this file using a UI.
Do you have ideas for the UI ? Can  a pyGTK UI be good ?

**Comment by Mte90** [comment]
For me also a web version is not a problem.
Anyway I am an huge fan of PyQT so if I have to maintain  I prefer that (https://github.com/Mte90/PyQT-Boilerplate).
