### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by Mte90** [Mte90/SyntaxAutoFix#27]
In that way is not required anymore to use as mandatory all the parameters and is possible to use also more dictionaries instead only 2.

**Comment by rgaduput** [comment]
Does it mean the script will load user inputs from config file and not using parameters like now ?

**Comment by Mte90** [comment]
My idea is to leave both where the parameters can overwrite the config instructions.
In that way is possible to have a global setting and custom usage.

**Comment by shubhambhattar** [comment]
Can you provide the default values of `words_file` and `words_file2` that you want in config file?

**Comment by Mte90** [comment]
You can see them in the readme file :-)

**Comment by shubhambhattar** [comment]
@Mte90 I don't quite understand the requirement. If I am adding custom terms to the config file, then whenever user wants to change those terms, the user will have to edit the config file anyway. Or I am missing something? Also, I am not quite sure what you exactly mean by saying `custom terms`?

**Comment by Mte90** [comment]
My idea is that the dictionaries are something available as global and you should have access to edit or you don't want to broken them with an update.
So in case someone has custom words that are not available on the dictionaries he should be able to add more of them, so in my idea the config file is the perfect solution.
