### ISSUE TITLE
PyPi package support

### ISSUE THREAD

**Issue by Mte90** [Mte90/SyntaxAutoFix#41]
The files to create a pypi package and publish so we can official promote that tool.

**Comment by Yagueteiro** [comment]
Hi, I would be interested in working on this

**Comment by Mte90** [comment]
So it is yours :-)

**Comment by Yagueteiro** [comment]
Sorry, I'm not too sure on what exactly you want. 

Do you want it to be used as a module which can be imported? If so, how do you want it to work? If this is the case, I'd suggest something like this:
```
from SyntaxAutoFix import syntaxalert
syntaxalert.start()
```

Sorry if I misunderstood something.

**Comment by Mte90** [comment]
No I want that is downloadable by pip so the project require the `setup.py` files and so on.
